ALTER DATABASE PriceCompareDB
SET SINGLE_USER WITH ROLLBACK IMMEDIATE

USE master;
GO
ALTER DATABASE PriceCompareDB
COLLATE Hebrew_CI_AS ;
GO

ALTER DATABASE PriceCompareDB
SET MULTI_USER WITH ROLLBACK IMMEDIATE