//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PriceCompareModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class item
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public item()
        {
            this.prices = new HashSet<price>();
        }
    
        public long item_code { get; set; }
        public string item_type { get; set; }
        public string item_name { get; set; }
        public string manufacturer_name { get; set; }
        public string manufacturer_item_description { get; set; }
        public string unit_quantity { get; set; }
        public string quantity_in_package { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<price> prices { get; set; }

        public override string ToString()
        {
            return item_name;
        }
    }
}
