//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PriceCompareModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class price
    {
        public int item_id { get; set; }
        public int store_id { get; set; }
        public Nullable<float> price1 { get; set; }
        public string unit_of_measure { get; set; }
    
        public virtual item item { get; set; }
        public virtual store store { get; set; }
    }
}
